version: '3'

services:
  db:
    build: postgres/.
    expose:
      - 5432
    ports:
      - 5432:5432
  app:
    build: app/.
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - db